[package]
name = "fest"
authors = ["Jonas Platte <mail@jonasplatte.de>"]
license = "GPL-3.0+"
version = "0.1.0"
repository = "https://github.com/fest-im/fest"
build = "build/build.rs"

[dependencies]
futures-await = "0.1.0"
gio = "0.4.0"
glib = "0.5.0"
hyper = "0.11.24"
tokio-core = "0.1.16"
url = "1.7.0"

[dependencies.gtk]
features = ["v3_16"]
version = "0.4.0"

[dependencies.ruma-client]
git = "https://github.com/jplatte/ruma-client.git"
branch = "synapse-workarounds"
